export enum USER_ACTION_TYPES {
	FETCH_USER_DETIALS_START = 'user/FETCH_USER_DETAILS_START',
	SET_CURRENT_USER_ID = 'user/SET_CURRENT_USER_ID',
	FETCH_USER_DETAILS_SUCCESS = 'user/FETCH_USER_DETAILS_SUCCESS',
    FETCH_USER_DETAILS_FAILED = 'user/FETCH_USER_DETAILS_FAILED',
    FOLLOW_USER_START = 'user/FOLLOW_USER_START',
    FOLLOW_USER_SUCCESS = 'user/FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILED = 'user/FOLLOW_USER_FAILED',
    UNFOLLOW_USER_START = 'user/UNFOLLOW_USER_START',
    UNFOLLOW_USER_SUCCESS = 'user/UNFOLLOW_USER_SUCCESS',
    UNFOLLOW_USER_FAILED = 'user/UNFOLLOW_USER_FAILED',
    UPDATE_PROFILE_START = 'user/UPDATE_PROFILE_START',
    UPDATE_PROFILE_SUCCESS = 'user/UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAILED = 'user/UPDATE_PROFILE_FAILED',
    CHANGE_AVATAR_START = 'user/CHANGE_AVATAR_START',
    CHANGE_AVATAR_SUCCESS = 'user/CHANGE_AVATAR_SUCCESS',
    CHANGE_AVATAR_FAILED = 'user/CHANGE_AVATAR_FAILED',
    RESET = 'user/RESET',
}

export type User = {

    id: string;
    displayName: string;
    username: string;
    email: string;
    avatar: string;
    bio: string;
    isFollowed: boolean;
};
