export enum USER_ACTION_TYPES {

	CHECK_USER_SESSION = 'user/CHECK_USER_SESSION',
	USER_SIGN_IN_SUCCESS = 'user/FETCH_USER_SUCCESS',
	USER_SIGN_IN_FAILED = 'user/FETCH_USER_FAILED',
    FETCH_USER_DETIALS_START = 'user/FETCH_USER_DETAILS_START',
    USER_NOT_REGISTERED = 'user/USER_NOT_REGISTERED',
    REGISTER_USER_START = 'user/REGISTER_USER_START',
    REGISTER_USER_SUCCESS = 'user/REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILED = 'user/REGISTER_USER_FAILED',
    FETCH_USER_DETAILS_SUCCESS = 'user/FETCH_USER_DETAILS_SUCCESS',
    FETCH_USER_DETAILS_FAILED = 'user/FETCH_USER_DETAILS_FAILED',
}

export type User = {
    
	id: string;
	username: string;
	profilePicture: string;
};
