export enum USER_ACTION_TYPES {
	FETCH_USER_DETIALS_START = 'user/FETCH_USER_DETAILS_START',
	SET_CURRENT_USER_ID = 'user/SET_CURRENT_USER_ID',
	FETCH_USER_DETAILS_SUCCESS = 'user/FETCH_USER_DETAILS_SUCCESS',
    FETCH_USER_DETAILS_FAILED = 'user/FETCH_USER_DETAILS_FAILED',
    FOLLOW_USER_START = 'user/FOLLOW_USER_START',
    FOLLOW_USER_SUCCESS = 'user/FOLLOW_USER_SUCCESS',
    FOLLOW_USER_FAILED = 'user/FOLLOW_USER_FAILED',
    UNFOLLOW_USER_START = 'user/UNFOLLOW_USER_START',
    UNFOLLOW_USER_SUCCESS = 'user/UNFOLLOW_USER_SUCCESS',
    UNFOLLOW_USER_FAILED = 'user/UNFOLLOW_USER_FAILED',
}

export type User = {

    id: string;
    displayName: string;
	username: string;
    avatar: string;
    bio: string;
    isFollowed: boolean;
};
